### ISSUE TITLE
Readline/history

### ISSUE THREAD

**Issue by Remi-Jacobs** [DanSam5K/mini-shell-project#35]
Readline function is not used in our code and because of the we don't have the history function/capability. We can manually create history (I have made a version) but for it to work like bash we will have to make it a builtin function which is beyond the scope of the project.
Also our prompt line (CLI) does does not have editing capabilities also due to us not implementing readline

**Comment by DanSam5K** [comment]
@Remi-Jacobs, Kindly, describe this feature provide technical specification, acceptance criteria this makes it easy to work on, since you understand the feat more! thanks

**Comment by Remi-Jacobs** [comment]
Implemented history function
